### ISSUE TITLE
S. 35 — Bei den Modulen davor ist immer ein Punkt nach »schreiben«.

### ISSUE THREAD

**Issue by Eric-BueroBumBum** [Eric-BueroBumBum/rz_edulab_18#10]
https://github.com/Eric-BueroBumBum/rz_edulab_18/issues/new

**Comment by Eric-BueroBumBum** [comment]
<img width="479" alt="bildschirmfoto 2018-05-03 um 13 05 39" src="https://user-images.githubusercontent.com/20647049/39582667-bb804b7e-4eee-11e8-8a1c-9d38a5609fc3.png">

**Comment by SebastianBareis** [comment]
√
