### ISSUE TITLE
S. 25 — Leerraum zu groß

### ISSUE THREAD

**Issue by Eric-BueroBumBum** [Eric-BueroBumBum/rz_edulab_18#12]
<img width="527" alt="bildschirmfoto 2018-05-03 um 16 27 45" src="https://user-images.githubusercontent.com/20647049/39582805-05a2146c-4eef-11e8-974e-f4a794eb1481.png">

**Comment by SebastianBareis** [comment]
Das ist immer so. Bei allen Tabellen. Die letzte Zeile ist immer etwas größer.
Hmm. Denkst du das sieht aus wie ein Fehler?

**Comment by SebastianBareis** [comment]
![bildschirmfoto 2018-05-03 um 17 07 14](https://user-images.githubusercontent.com/38954143/39585191-7cbbd614-4ef4-11e8-8f46-44d9b691458e.png)

Ist dann wieder schwierig mit der BU

**Comment by Eric-BueroBumBum** [comment]
Ja.
Hat ja keinen Sinn.
Eure Absatzlinien sind Javanisch enger dran.

Von meinem iPhone gesendet

**Comment by SebastianBareis** [comment]
Ich mache es anders.
Linie bekommt den gleichen Abstand.
BU ist dann aber in diesen 3 Fällen nicht mehr im Grundlinienraster.

**Comment by SebastianBareis** [comment]
![bildschirmfoto 2018-05-03 um 17 22 58](https://user-images.githubusercontent.com/38954143/39586124-a7b25b52-4ef6-11e8-8d48-3d254d3c473b.png)

**Comment by Eric-BueroBumBum** [comment]
😂
Büro Bum Bum
Visuelle Kommunikation
Eric Dannebaum
Müllerstraße 138 D, 1. HH, 3. OG
13353 Berlin–Wedding
–––
Büro   +49 (0) 30 40 50 22 00
Mobil  +49 (0) 162 95 65 918
–––
eric@buerobumbum.com
www.buerobumbum.com NEW!
