### ISSUE TITLE
S. 27 — Hier auch noch mal Leerraum (schon gemacht?)

### ISSUE THREAD

**Issue by Eric-BueroBumBum** [Eric-BueroBumBum/rz_edulab_18#14]
<img width="627" alt="bildschirmfoto 2018-05-04 um 10 53 55" src="https://user-images.githubusercontent.com/20647049/39619851-848b6450-4f89-11e8-84d5-7a3159691cab.png">

**Comment by SebastianBareis** [comment]
ja. und auf seite 47 auch
